name: Grocery CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests and Deploy
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Stop Running Services
        run: pm2 stop all || true

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm install

      - name: Build Frontend
        working-directory: ./frontend
        run: npm run build

      - name: Run Backend Tests
        working-directory: ./backend
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}
        run: npm test

      - name: Create Backend .env File
        working-directory: ./backend
        run: |
          touch .env
          echo "${{ secrets.PROD }}" > .env

      - name: Restart Services
        run: |
          pm2 start all || true
          pm2 restart all
